### ISSUE TITLE
Needs an example, demo or screenshot

### ISSUE THREAD

**Issue by elsbrock** [caltechads/django-wildewidgets#1]
Hey, this looks very interesting, but I would love to see how it looks like. Can you add a screenshot, maybe even a demo or example app? Thanks.

**Comment by glennbach** [comment]
Yeah, I know. That's a work in progress, in addition to more extensive docs. It's pretty stable now, so my plan is to move to 1.0, but that's predicated on more docs. I'm glad you reached out, because I wasn't thinking of adding screenshots, but that might be a stopgap measure until we can write a demo.

**Comment by glennbach** [comment]
I threw a couple quick screenshots into the readthedocs index page. It's not much...

**Comment by caltechads** [comment]
I've deployed an initial demo at https://wildewidgets.caltech.edu/.

**Comment by elsbrock** [comment]
Cool, thanks!
